# Generated by Django 3.2.8 on 2021-11-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investorstartupplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('points', models.TextField()),
                ('decision', models.IntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investorstartupplan.investorprofile')),
            ],
        ),
    ]
