# Generated by Django 3.2.8 on 2021-10-11 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startupname', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('T', 'Tech'), ('A', 'Agricultural'), ('E', 'ECommerce'), ('M', 'Medical'), ('O', 'Others')], max_length=1)),
                ('description', models.TextField()),
                ('vision', models.TextField()),
                ('startedDate', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(max_length=20)),
                ('Datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
