# Generated by Django 3.2.8 on 2021-11-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupsContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('email2', models.EmailField(blank=True, max_length=256, null=True)),
                ('website', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('fb_page', models.CharField(blank=True, max_length=550, null=True)),
                ('ig_ac', models.CharField(blank=True, max_length=550, null=True)),
                ('linkedin_ac', models.CharField(blank=True, max_length=550, null=True)),
                ('twitter_ac', models.CharField(blank=True, max_length=550, null=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startupsinfo')),
            ],
        ),
    ]
