# Generated by Django 3.2.8 on 2021-11-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0002_startupscontactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startupsinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone_no', models.CharField(max_length=256)),
                ('photo', models.CharField(max_length=256)),
                ('roles', models.TextField()),
                ('if_exists', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StartupClaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startups.startupsinfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
