# Generated by Django 3.2.8 on 2021-11-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startupclaps_startupteams_startupviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('images', models.CharField(blank=True, max_length=256, null=True)),
                ('startup_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupteams')),
            ],
        ),
    ]
