# Generated by Django 3.2.8 on 2021-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('I', 'Individual'), ('S', 'Startup')], max_length=1),
        ),
    ]
