# Generated by Django 3.2.8 on 2021-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='intrests',
            field=models.CharField(choices=[('S', 'Startups'), ('P', 'Programming'), ('O', 'Others')], max_length=1),
        ),
    ]
