# Generated by Django 3.2.8 on 2021-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userinfos_intrests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='others',
            field=models.TextField(default='Add Others Field...'),
        ),
    ]
