# Generated by Django 3.1.7 on 2021-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211107_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='picture',
            field=models.ImageField(default='default.png', max_length=256, upload_to=''),
        ),
    ]
