# Generated by Django 3.2.8 on 2021-11-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('middlename', models.CharField(blank=True, max_length=256, null=True)),
                ('lastname', models.CharField(max_length=256)),
                ('invited_by', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupMeets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('venue', models.CharField(max_length=256)),
                ('occupancy', models.IntegerField()),
                ('banner', models.CharField(blank=True, max_length=256, null=True)),
                ('theme', models.CharField(max_length=256)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StartupRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('no_of_attendes', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartupMeets.startupmeets')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StartupMeets.startupregistration')),
            ],
        ),
        migrations.CreateModel(
            name='GuestMeets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartupMeets.guestspeaker')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StartupMeets.startupmeets')),
            ],
        ),
    ]
