# Generated by Django 3.2.8 on 2021-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('inspirations', models.TextField()),
                ('favourite_quote', models.CharField(max_length=555)),
                ('profile_picture', models.CharField(max_length=256)),
            ],
        ),
    ]
